input_data_path: "data/raw/heart.csv"
output_model_path: "models/logistic_regression.pkl"
output_transformer_path: "models/transformer.pkl"
logger_config: "configs/logging_config.yaml"
split_params:
  validation_size: 0.25
  random_state: 17
feature_params:
  categorical_features: ['sex', 'cp', 'restecg', 'exang', 'slope', 'fbs', 'ca', 'thal']
  numerical_features: ['age', 'chol', 'thalach', 'oldpeak', 'trestbps']
  target: 'target'
model_params:
  model_type: "Logistic Regression"
  random_state: 17
  n_jobs: -1
  max_iter: 200