logger_config: "configs/logging_config.yaml"

input_data_predict_path: "data/raw/heart.csv"
output_data_predict_path: "models/predicts.csv"
output_model_path: "models/random_forest.pkl"
output_transformer_path: "models/transformer.pkl"
